### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Comma8** [lagomorph/gbaccount#1]
Any chance you wouldn't mind adding some comments to this? In particular explaining the loop inside the validation and accountNumber functions? I see what it's doing but have no idea why. Thanks in advance!

**Comment by lagomorph** [comment]
Hey, thanks for the feedback. I've added some details of the algorithm. See what you think. I'm not sure it's known why the specific bit manipulation is done the way it is to generate the check digit. I'd guess it was considered "good enough" to make the account generation not trivially predictable.
